# Generated by Django 3.2 on 2021-05-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OPAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('meet_criteria_therapy', models.BooleanField(default=False)),
                ('front_door', models.BooleanField(default=False)),
                ('RAFT', models.BooleanField(default=False)),
                ('CCMT', models.BooleanField(default=False)),
                ('CCMT_Date', models.DateField(blank=True, null=True)),
                ('admission_barthel', models.IntegerField(blank=True, null=True)),
                ('discharge_barthel', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPAL.patient')),
                ('referral_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.referralsource')),
            ],
        ),
    ]
