# Generated by Django 3.2 on 2021-05-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPAL', '0001_initial'),
        ('services', '0004_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='therapist_referring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OPAL.therapist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='type_of_referral',
            field=models.CharField(default='nice', max_length=50),
            preserve_default=False,
        ),
    ]
