# Generated by Django 3.2 on 2021-05-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndirectInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('postcode', models.CharField(max_length=8)),
                ('locality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('therapist_role', models.CharField(choices=[('TA', 'Therapy Assistant'), ('OT', 'Occupation Therapist'), ('PT', 'Physio Therapist')], default='TA', max_length=2)),
                ('band', models.IntegerField(default=1)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPAL.team')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehab', models.BooleanField(default=False)),
                ('direct_time', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('indirect_time', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('direct_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPAL.directinput')),
                ('indirect_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPAL.indirectinput')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPAL.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPAL.therapist')),
            ],
            options={
                'verbose_name_plural': 'Therapies',
            },
        ),
    ]
